kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: staff
  name: staff
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicassets", "pods"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]